---
title: "The effect of depth on decomposition"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Let's be convincing

Half of the world's organic carbon (C) is located below 20 cm, but the mechanisms behind the creation and retention of this organic C are unclear, especially considering that most organic C sources are concentrated above 20 cm or aboveground.  

As we move deeper into the soil and further from the soil surface, temperature, moisture, O2 availability, texture, pH, and even root tissue composition change.  These environmental properties and their interactions with each other can be described as one factor: *depth*.  There are large differences in the amount of organic matter with location in the soil profile due to both the amount of plant litter input and the effect of depth on decomposition rates and organic matter stabilization. Inputs can be easily measured and compared     

Depth is an emergent property that cannot be recreated in a laboratory, yet much of what we know about decomposition at depth is dependent upon laboratory studies with carefully controlled conditions.  The rest of what we know about the effect of depth comes from in-field studies that used litter bags to measure decomposition.  Litter bags introduce major problems relevant to decomposition, mainly that they restrict contact between soil and organic matter, greatly reducing the ability of microorganisms to reach and catabolize organic matter.  

This experiment seeks to examine the effect of depth on decomposition without physically controlling the components that make up depth and without creating an artificial environment such as that found inside litter bags. This examination will include analysis focused on the components that contribute to the depth effect.  

Two questions:

1. How does _litter quality_ affect the proportions of organic matter lost as DOC, CO2, and POM?  
2. How does 



This experiment
Decomp rate
DOC, CO2
O2, temp, moisture
CN
POM
